"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Events",
      [
        {
          hostId: 22,
          venueId: 9,
          typeId: 19,
          name: "Grass-roots didactic neural-net",
          date: "Tue Apr 05 2022",
          capacity: 350,
        },
        {
          hostId: 44,
          venueId: 29,
          typeId: 6,
          name: "Re-engineered 24 hour framework",
          date: "Fri Apr 29 2022",
          capacity: 650,
        },
        {
          hostId: 42,
          venueId: 1,
          typeId: 14,
          name: "Enterprise-wide fresh-thinking frame",
          date: "Sat Apr 30 2022",
          capacity: 950,
        },
        {
          hostId: 49,
          venueId: 39,
          typeId: 29,
          name: "Decentralized 24/7 contingency",
          date: "Sun May 01 2022",
          capacity: 100,
        },
        {
          hostId: 47,
          venueId: 4,
          typeId: 29,
          name: "Visionary analyzing interface",
          date: "Thu Apr 14 2022",
          capacity: 150,
        },
        {
          hostId: 29,
          venueId: 3,
          typeId: 7,
          name: "Organic context-sensitive process improvement",
          date: "Mon Aug 15 2022",
          capacity: 450,
        },
        {
          hostId: 15,
          venueId: 13,
          typeId: 13,
          name: "Ameliorated regional challenge",
          date: "Sun Apr 10 2022",
          capacity: 950,
        },
        {
          hostId: 42,
          venueId: 13,
          typeId: 18,
          name: "Managed static throughput",
          date: "Wed Nov 09 2022",
          capacity: 350,
        },
        {
          hostId: 13,
          venueId: 10,
          typeId: 7,
          name: "Future-proofed systemic local area network",
          date: "Sat Feb 18 2023",
          capacity: 1000,
        },
        {
          hostId: 37,
          venueId: 20,
          typeId: 2,
          name: "Implemented encompassing definition",
          date: "Sun Sep 04 2022",
          capacity: 650,
        },
        {
          hostId: 38,
          venueId: 20,
          typeId: 1,
          name: "Advanced empowering service-desk",
          date: "Mon Feb 13 2023",
          capacity: 65,
        },
        {
          hostId: 15,
          venueId: 37,
          typeId: 28,
          name: "Upgradable needs-based concept",
          date: "Fri Dec 02 2022",
          capacity: 450,
        },
        {
          hostId: 21,
          venueId: 34,
          typeId: 10,
          name: "Fully-configurable intangible encoding",
          date: "Sun May 08 2022",
          capacity: 900,
        },
        {
          hostId: 43,
          venueId: 17,
          typeId: 1,
          name: "Optimized local customer loyalty",
          date: "Sun Nov 13 2022",
          capacity: 800,
        },
        {
          hostId: 12,
          venueId: 19,
          typeId: 15,
          name: "Automated responsive artificial intelligence",
          date: "Mon May 16 2022",
          capacity: 900,
        },
        {
          hostId: 14,
          venueId: 5,
          typeId: 1,
          name: "Optimized 24/7 open system",
          date: "Sat Nov 26 2022",
          capacity: 600,
        },
        {
          hostId: 7,
          venueId: 25,
          typeId: 25,
          name: "Open-source asymmetric portal",
          date: "Fri May 06 2022",
          capacity: 900,
        },
        {
          hostId: 47,
          venueId: 28,
          typeId: 15,
          name: "Reverse-engineered human-resource workforce",
          date: "Wed Jun 22 2022",
          capacity: 500,
        },
        {
          hostId: 45,
          venueId: 7,
          typeId: 12,
          name: "Team-oriented multimedia flexibility",
          date: "Sat Oct 15 2022",
          capacity: 55,
        },
        {
          hostId: 32,
          venueId: 18,
          typeId: 1,
          name: "Universal needs-based knowledge base",
          date: "Mon Nov 07 2022",
          capacity: 950,
        },
        {
          hostId: 25,
          venueId: 39,
          typeId: 27,
          name: "Persistent maximized policy",
          date: "Sun May 01 2022",
          capacity: 1000,
        },
        {
          hostId: 32,
          venueId: 27,
          typeId: 29,
          name: "Stand-alone global website",
          date: "Wed Apr 13 2022",
          capacity: 150,
        },
        {
          hostId: 49,
          venueId: 2,
          typeId: 5,
          name: "Visionary needs-based system engine",
          date: "Tue Sep 27 2022",
          capacity: 450,
        },
        {
          hostId: 48,
          venueId: 30,
          typeId: 14,
          name: "Managed upward-trending software",
          date: "Sun Dec 25 2022",
          capacity: 850,
        },
        {
          hostId: 40,
          venueId: 6,
          typeId: 7,
          name: "De-engineered neutral budgetary management",
          date: "Wed Aug 03 2022",
          capacity: 70,
        },
        {
          hostId: 45,
          venueId: 9,
          typeId: 4,
          name: "Integrated discrete middleware",
          date: "Mon Mar 21 2022",
          capacity: 250,
        },
        {
          hostId: 47,
          venueId: 33,
          typeId: 18,
          name: "Mandatory global groupware",
          date: "Thu Dec 22 2022",
          capacity: 200,
        },
        {
          hostId: 38,
          venueId: 30,
          typeId: 10,
          name: "Self-enabling regional alliance",
          date: "Sat Jan 28 2023",
          capacity: 700,
        },
        {
          hostId: 5,
          venueId: 35,
          typeId: 12,
          name: "Programmable actuating groupware",
          date: "Sat Dec 17 2022",
          capacity: 650,
        },
        {
          hostId: 29,
          venueId: 6,
          typeId: 22,
          name: "Ergonomic next generation product",
          date: "Tue Nov 08 2022",
          capacity: 200,
        },
        {
          hostId: 28,
          venueId: 36,
          typeId: 24,
          name: "Optional value-added contingency",
          date: "Wed Jan 18 2023",
          capacity: 250,
        },
        {
          hostId: 5,
          venueId: 29,
          typeId: 15,
          name: "Organized dynamic strategy",
          date: "Fri May 13 2022",
          capacity: 950,
        },
        {
          hostId: 42,
          venueId: 15,
          typeId: 18,
          name: "Multi-layered multimedia parallelism",
          date: "Tue Aug 16 2022",
          capacity: 900,
        },
        {
          hostId: 16,
          venueId: 22,
          typeId: 11,
          name: "Extended executive database",
          date: "Sun Mar 05 2023",
          capacity: 350,
        },
        {
          hostId: 43,
          venueId: 9,
          typeId: 6,
          name: "Focused zero defect firmware",
          date: "Thu May 12 2022",
          capacity: 500,
        },
        {
          hostId: 34,
          venueId: 27,
          typeId: 4,
          name: "Fundamental eco-centric definition",
          date: "Fri Mar 03 2023",
          capacity: 900,
        },
        {
          hostId: 28,
          venueId: 20,
          typeId: 3,
          name: "Persistent multi-tasking instruction set",
          date: "Sun Dec 25 2022",
          capacity: 200,
        },
        {
          hostId: 23,
          venueId: 2,
          typeId: 27,
          name: "Implemented optimal secured line",
          date: "Mon Feb 13 2023",
          capacity: 200,
        },
        {
          hostId: 46,
          venueId: 25,
          typeId: 14,
          name: "Up-sized empowering database",
          date: "Tue Oct 25 2022",
          capacity: 650,
        },
        {
          hostId: 45,
          venueId: 31,
          typeId: 27,
          name: "Object-based coherent initiative",
          date: "Sat Feb 18 2023",
          capacity: 900,
        },
        {
          hostId: 24,
          venueId: 31,
          typeId: 6,
          name: "Synchronised explicit budgetary management",
          date: "Mon Feb 06 2023",
          capacity: 550,
        },
        {
          hostId: 15,
          venueId: 1,
          typeId: 25,
          name: "Robust high-level implementation",
          date: "Sat Jul 09 2022",
          capacity: 800,
        },
        {
          hostId: 26,
          venueId: 9,
          typeId: 19,
          name: "Seamless exuding pricing structure",
          date: "Tue Jun 21 2022",
          capacity: 900,
        },
        {
          hostId: 43,
          venueId: 4,
          typeId: 1,
          name: "Universal dynamic parallelism",
          date: "Wed Feb 01 2023",
          capacity: 550,
        },
        {
          hostId: 20,
          venueId: 20,
          typeId: 5,
          name: "Progressive web-enabled archive",
          date: "Wed Oct 26 2022",
          capacity: 200,
        },
        {
          hostId: 5,
          venueId: 39,
          typeId: 20,
          name: "Universal exuding adapter",
          date: "Sun Mar 20 2022",
          capacity: 300,
        },
        {
          hostId: 28,
          venueId: 15,
          typeId: 8,
          name: "Ergonomic composite workforce",
          date: "Wed Apr 06 2022",
          capacity: 350,
        },
        {
          hostId: 14,
          venueId: 18,
          typeId: 27,
          name: "Team-oriented zero defect challenge",
          date: "Fri Dec 09 2022",
          capacity: 450,
        },
        {
          hostId: 22,
          venueId: 9,
          typeId: 8,
          name: "Advanced mobile installation",
          date: "Fri Apr 15 2022",
          capacity: 500,
        },
        {
          hostId: 10,
          venueId: 31,
          typeId: 17,
          name: "Intuitive grid-enabled workforce",
          date: "Fri Oct 07 2022",
          capacity: 700,
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:

    */ return queryInterface.bulkDelete("Events", null, {});
  },
};
