"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Venues",
      [
        {
          name: "Mayert - Shanahan",
          address: "394 Beier Trail",
          city: "East Scarlettborough",
          state: "Montana",
          zipCode: "39003",
          lat: "66.7756",
          long: "104.2029",
        },
        {
          name: "Green and Sons",
          address: "5829 Elmore Orchard",
          city: "Kaceybury",
          state: "Maine",
          zipCode: "43407-1071",
          lat: "78.9359",
          long: "93.6336",
        },
        {
          name: "Brakus - Mante",
          address: "4011 Bailey Branch",
          city: "Betteburgh",
          state: "Vermont",
          zipCode: "63959-5937",
          lat: "-6.4338",
          long: "-53.0702",
        },
        {
          name: "Adams, Pfannerstill and Kuhn",
          address: "4797 Bergnaum Fork",
          city: "McGlynnchester",
          state: "Pennsylvania",
          zipCode: "42610-4535",
          lat: "75.7703",
          long: "-35.8890",
        },
        {
          name: "Corwin - White",
          address: "2426 Braun River",
          city: "North Doyleburgh",
          state: "Tennessee",
          zipCode: "18964-9485",
          lat: "-48.8453",
          long: "3.4157",
        },
        {
          name: "Herman and Sons",
          address: "70081 Gladyce Roads",
          city: "Lake Hollie",
          state: "Georgia",
          zipCode: "62462-3168",
          lat: "47.0614",
          long: "69.5872",
        },
        {
          name: "Boyle - Wilderman",
          address: "00605 Augusta Forges",
          city: "Ceasarberg",
          state: "Utah",
          zipCode: "24172",
          lat: "12.5119",
          long: "21.2700",
        },
        {
          name: "Herman, Anderson and Kihn",
          address: "795 Bruen Knoll",
          city: "Lynchburg",
          state: "Missouri",
          zipCode: "60945-2918",
          lat: "-0.0848",
          long: "43.8948",
        },
        {
          name: "Koss Group",
          address: "364 Alyson Underpass",
          city: "Denesikfort",
          state: "California",
          zipCode: "39738",
          lat: "-77.0778",
          long: "-25.2171",
        },
        {
          name: "Schinner - Becker",
          address: "621 Bernice Mountain",
          city: "Lindgrenville",
          state: "Kentucky",
          zipCode: "22194",
          lat: "-66.8533",
          long: "-60.7604",
        },
        {
          name: "Hegmann Group",
          address: "385 Gerhard Mission",
          city: "New Ernamouth",
          state: "Iowa",
          zipCode: "20363-6522",
          lat: "5.6272",
          long: "-44.5577",
        },
        {
          name: "Gleason - Miller",
          address: "10311 Ernser Port",
          city: "Garden Grove",
          state: "North Carolina",
          zipCode: "24524",
          lat: "-46.1366",
          long: "145.6174",
        },
        {
          name: "Schneider LLC",
          address: "509 Kyla Plain",
          city: "Lake Vivian",
          state: "Wisconsin",
          zipCode: "42687",
          lat: "11.6520",
          long: "-54.8283",
        },
        {
          name: "Satterfield - Ryan",
          address: "3350 Rylee Terrace",
          city: "Surprise",
          state: "Nevada",
          zipCode: "31578",
          lat: "74.8707",
          long: "178.1191",
        },
        {
          name: "Ledner - Herzog",
          address: "73407 Brown Mews",
          city: "Lake Waldohaven",
          state: "Rhode Island",
          zipCode: "54379-4847",
          lat: "13.8626",
          long: "-142.0751",
        },
        {
          name: "Heathcote - Homenick",
          address: "58659 Schowalter Lakes",
          city: "Lakewood",
          state: "Mississippi",
          zipCode: "16188-0790",
          lat: "-23.3567",
          long: "-38.8197",
        },
        {
          name: "Maggio, Hagenes and Christiansen",
          address: "326 Jorge Locks",
          city: "Port Electa",
          state: "Missouri",
          zipCode: "16449",
          lat: "-29.5857",
          long: "-110.4156",
        },
        {
          name: "Klein, Goodwin and Rau",
          address: "0841 Walter Coves",
          city: "Lake Paulineside",
          state: "Arkansas",
          zipCode: "24212-8369",
          lat: "61.4117",
          long: "49.4481",
        },
        {
          name: "O'Conner, Mueller and Ward",
          address: "4852 Destin Junctions",
          city: "Thornton",
          state: "North Carolina",
          zipCode: "84603",
          lat: "2.1041",
          long: "-83.7146",
        },
        {
          name: "Hamill - MacGyver",
          address: "266 Roberts Garden",
          city: "Brendatown",
          state: "Iowa",
          zipCode: "28214-8608",
          lat: "81.9896",
          long: "55.9904",
        },
        {
          name: "Zulauf LLC",
          address: "9856 Keeling Forges",
          city: "Ernestinamouth",
          state: "Washington",
          zipCode: "03926",
          lat: "33.4620",
          long: "146.3122",
        },
        {
          name: "Satterfield - Stiedemann",
          address: "5226 Batz Court",
          city: "Rubyetown",
          state: "Texas",
          zipCode: "57204",
          lat: "78.8173",
          long: "-64.7914",
        },
        {
          name: "Gutmann LLC",
          address: "94636 Gorczany Burgs",
          city: "Lynchburg",
          state: "Texas",
          zipCode: "87236",
          lat: "23.5941",
          long: "57.6171",
        },
        {
          name: "Olson, Bernier and Runte",
          address: "32369 Romaguera Roads",
          city: "South Melvinamouth",
          state: "Massachusetts",
          zipCode: "34728-2971",
          lat: "-8.0633",
          long: "-110.3690",
        },
        {
          name: "Lueilwitz, Grant and Satterfield",
          address: "884 Sarina Stream",
          city: "Louisaborough",
          state: "Nevada",
          zipCode: "82817-0440",
          lat: "-12.4837",
          long: "-59.3892",
        },
        {
          name: "Hamill and Sons",
          address: "93615 Mylene Orchard",
          city: "Mertzfurt",
          state: "Montana",
          zipCode: "51790",
          lat: "11.0874",
          long: "81.1450",
        },
        {
          name: "Jerde, Stanton and Johnston",
          address: "953 Yost Manors",
          city: "Bauchport",
          state: "Texas",
          zipCode: "59788",
          lat: "-81.8068",
          long: "-3.2489",
        },
        {
          name: "Graham, Brekke and Cruickshank",
          address: "387 Marisol View",
          city: "Shreveport",
          state: "Idaho",
          zipCode: "66726-1742",
          lat: "-54.9485",
          long: "31.3595",
        },
        {
          name: "Barrows, Rohan and Mosciski",
          address: "51910 Amira Port",
          city: "Burke",
          state: "Illinois",
          zipCode: "02399-9393",
          lat: "-40.5830",
          long: "-84.3753",
        },
        {
          name: "Cremin - Hyatt",
          address: "2678 Thompson Extensions",
          city: "Lake Demarcus",
          state: "North Carolina",
          zipCode: "71477-4197",
          lat: "-77.7266",
          long: "-120.9667",
        },
        {
          name: "Mayer, Romaguera and Harvey",
          address: "2493 Griffin Mountain",
          city: "El Cajon",
          state: "Wyoming",
          zipCode: "86086-5113",
          lat: "-16.8391",
          long: "60.0554",
        },
        {
          name: "Jakubowski, Schamberger and Corwin",
          address: "354 Madilyn Spring",
          city: "New Milo",
          state: "North Carolina",
          zipCode: "78244-8007",
          lat: "-89.0743",
          long: "-168.3120",
        },
        {
          name: "Toy - Jenkins",
          address: "0035 Deon Track",
          city: "Jonatanberg",
          state: "Massachusetts",
          zipCode: "66267",
          lat: "-11.4099",
          long: "-67.4959",
        },
        {
          name: "Cruickshank, Leuschke and Weissnat",
          address: "12173 Buckridge Point",
          city: "Pflugerville",
          state: "Wyoming",
          zipCode: "45874-8283",
          lat: "-56.3810",
          long: "-113.8935",
        },
        {
          name: "Swaniawski, Hettinger and Reilly",
          address: "6219 Johnnie Corner",
          city: "Flint",
          state: "Arizona",
          zipCode: "14359",
          lat: "-89.8033",
          long: "96.4458",
        },
        {
          name: "Fritsch, Waters and Skiles",
          address: "7216 Katelynn Centers",
          city: "Lake Deborah",
          state: "Kansas",
          zipCode: "73036-0582",
          lat: "-64.4384",
          long: "-69.9179",
        },
        {
          name: "Wolff - Botsford",
          address: "6367 Kemmer Place",
          city: "Clintonchester",
          state: "New York",
          zipCode: "65307",
          lat: "78.8180",
          long: "-26.3973",
        },
        {
          name: "O'Kon - Dooley",
          address: "2121 Leannon Grove",
          city: "Port Laron",
          state: "Ohio",
          zipCode: "38859-5193",
          lat: "62.2116",
          long: "-143.5713",
        },
        {
          name: "Gaylord, Rath and Goodwin",
          address: "210 Rosendo Forges",
          city: "North Sonyastad",
          state: "New Hampshire",
          zipCode: "87301-0943",
          lat: "-46.9627",
          long: "73.9475",
        },
        {
          name: "Willms, Stokes and Ankunding",
          address: "704 Wyman Lane",
          city: "Port Katlynfort",
          state: "Utah",
          zipCode: "70821",
          lat: "36.2188",
          long: "-103.9253",
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Venues", null, {});
  },
};
